name: aste
channels:
  - conda-forge
dependencies:
    - python=3.8
# Basics
    - numpy
    - scipy
    - future
# xarray et al
    - xarray
    - netCDF4
    - bottleneck
    - dask
    - cftime
    - xmitgcm>=0.5.0
    - xgcm>=0.5.0
    - ecco_v4_py>=1.3.0
# plotting resampling
    - cartopy
    - cmocean
    - pyresample
# for other packages
    - cachetools
    - fsspec
    - zarr
    - coverage
    - pytest-cov 
    - codecov
    - black
    - docrep<=0.2.7
    - aiohttp
# jupyter etc
    - jupyter
    - ipython
    - ipykernel
